haschanged

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -39,3 +39,41 @@ isempty () (
   (( ${#files[@]} > 0 )) && return 1
   return 0
 )
+
+# usage: haschanged [-p] file [file...]
+
+haschanged () {
+  local parsable=false
+  if [[ $1 = "-p" ]] ; then
+    parsable=true
+    shift
+  fi
+  [[ $1 = -- ]] && shift
+  if ((!$#)) ; then
+    "$parsable" && echo 4 || echo "No file selected"
+    return 4
+  fi
+  local filename
+  local content
+  while (($#)) ; do
+    if [[ -f $1 ]]; then
+      filename=$(realpath "$1" | base64 | tr / _)
+      read hash _ <<< "$(sha1sum "$1")"
+      if [[ -f "/tmp/libash/$filename" ]] ; then
+        content=$(< "/tmp/libash/$filename")
+        if [[ $content = "$hash" ]] ; then
+          "$parsable" && echo 0 || echo "Not changed: $1"
+        else
+          "$parsable" && echo 1 || echo "File changed: $1"
+          echo "$hash" > "/tmp/libash/$filename"
+        fi
+      else
+        "$parsable" && echo 2 || echo "New file: $1"
+        echo "$hash" > "/tmp/libash/$filename"
+      fi
+    else
+      "$parsable" && echo 3 || echo "Not found: $1"
+    fi
+    shift
+  done
+}
